
##!--{"Name":"__mainfunction__","Type":null,"Key":"","Value":"resultdata = RecipeRun(gs_semimage1,gs_semimage2,gs_semimage3,gs_semimage4,gs_semimage5,gs_semimage6,gs_semimage7,gs_semimage8,gs_semimage9,gs_semimage10,gs_layercount,gs_layerimage1,gs_layerindex1,gs_refimage1,gs_refvector1,gs_layerimage2,gs_layerindex2,gs_refimage2,gs_refvector2,gs_layerimage3,gs_layerindex3,gs_refimage3,gs_refvector3,gs_layerimage4,gs_layerindex4,gs_refimage4,gs_refvector4,gs_layerimage5,gs_layerindex5,gs_refimage5,gs_refvector5,gs_layerimage6,gs_layerindex6,gs_refimage6,gs_refvector6,gs_layerimage7,gs_layerindex7,gs_refimage7,gs_refvector7,gs_layerimage8,gs_layerindex8,gs_refimage8,gs_refvector8,gs_layerimage9,gs_layerindex9,gs_refimage9,gs_refvector9,gs_layerimage10,gs_layerindex10,gs_refimage10,gs_refvector10,gs_layerimage11,gs_layerindex11,gs_refimage11,gs_refvector11,gs_layerimage12,gs_layerindex12,gs_refimage12,gs_refvector12,gs_layerimage13,gs_layerindex13,gs_refimage13,gs_refvector13,gs_layerimage14,gs_layerindex14,gs_refimage14,gs_refvector14,gs_layerimage15,gs_layerindex15,gs_refimage15,gs_refvector15,gs_layerimage16,gs_layerindex16,gs_refimage16,gs_refvector16,gs_layerimage17,gs_layerindex17,gs_refimage17,gs_refvector17,gs_layerimage18,gs_layerindex18,gs_refimage18,gs_refvector18,gs_layerimage19,gs_layerindex19,gs_refimage19,gs_refvector19,gs_layerimage20,gs_layerindex20,gs_refimage20,gs_refvector20,gs_resultimageurl,gs_resultdataurl,gs_resultimageextension,gs_waferid,gs_defectid,gs_xreal,gs_yreal,gs_scale,gs_xindex,gs_yindex,gs_particlecode,gs_angle,gs_clipimagewidth,gs_clipimageheight,gs_imagefov)","Category":"Others"}
##!--{"Name":"__templatename__","Type":"string","Key":"","Value":"daq_3_0","Category":"Others"}
##!--{"Name":"gs_semimage1","Type":"file","Key":"","Value":"D:\\TestSet\\daq\\test1\\sem\\1.tif","Category":"gs_semimage"}
##!--{"Name":"gs_semimage2","Type":"file","Key":"","Value":"","Category":"gs_semimage"}
##!--{"Name":"gs_semimage3","Type":"file","Key":"","Value":"","Category":"gs_semimage"}
##!--{"Name":"gs_semimage4","Type":"file","Key":"","Value":"","Category":"gs_semimage"}
##!--{"Name":"gs_semimage5","Type":"file","Key":"","Value":"","Category":"gs_semimage"}
##!--{"Name":"gs_semimage6","Type":"file","Key":"","Value":"","Category":"gs_semimage"}
##!--{"Name":"gs_semimage7","Type":"file","Key":"","Value":"","Category":"gs_semimage"}
##!--{"Name":"gs_semimage8","Type":"file","Key":"","Value":"","Category":"gs_semimage"}
##!--{"Name":"gs_semimage9","Type":"file","Key":"","Value":"","Category":"gs_semimage"}
##!--{"Name":"gs_semimage10","Type":"file","Key":"","Value":"","Category":"gs_semimage"}
##!--{"Name":"gs_layerimage1","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage2","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage3","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage4","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage5","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage6","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage7","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage8","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage9","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage10","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage11","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage12","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage13","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage14","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage15","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage16","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage17","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage18","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage19","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerimage20","Type":"file","Key":"","Value":"","Category":"gs_layerimage"}
##!--{"Name":"gs_layerindex1","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex2","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex3","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex4","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex5","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex6","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex7","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex8","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex9","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex10","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex11","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex12","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex13","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex14","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex15","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex16","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex17","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex18","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex19","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_layerindex20","Type":"string","Key":"","Value":"","Category":"gs_layerindex"}
##!--{"Name":"gs_refimage1","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage2","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage3","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage4","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage5","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage6","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage7","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage8","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage9","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage10","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage11","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage12","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage13","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage14","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage15","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage16","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage17","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage18","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage19","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refimage20","Type":"file","Key":"","Value":"","Category":"gs_refimage"}
##!--{"Name":"gs_refvector1","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector2","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector3","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector4","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector5","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector6","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector7","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector8","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector9","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector10","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector11","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector12","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector13","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector14","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector15","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector16","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector17","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector18","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector19","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_refvector20","Type":"file","Key":"","Value":"","Category":"gs_refvector"}
##!--{"Name":"gs_layercount","Type":"string","Key":"","Value":"0","Category":"Others"}
##!--{"Name":"gs_resultimageurl","Type":"directory","Key":"","Value":"","Category":"Others"}
##!--{"Name":"gs_resultdataurl","Type":"directory","Key":"","Value":"","Category":"Others"}
##!--{"Name":"gs_resultimageextension","Type":"string","Key":"","Value":".jpg","Category":"Others"}
##!--{"Name":"gs_waferid","Type":"string","Key":"","Value":"","Category":"Others"}
##!--{"Name":"gs_defectid","Type":"string","Key":"","Value":"1","Category":"Others"}
##!--{"Name":"gs_xreal","Type":"string","Key":"","Value":"0","Category":"Others"}
##!--{"Name":"gs_yreal","Type":"string","Key":"","Value":"0","Category":"Others"}
##!--{"Name":"gs_scale","Type":"string","Key":"","Value":"0","Category":"Others"}
##!--{"Name":"gs_xindex","Type":"string","Key":"","Value":"","Category":"Others"}
##!--{"Name":"gs_yindex","Type":"string","Key":"","Value":"","Category":"Others"}
##!--{"Name":"gs_particlecode","Type":"string","Key":"","Value":"","Category":"Others"}
##!--{"Name":"gs_angle","Type":"string","Key":"","Value":"0","Category":"Others"}
##!--{"Name":"gs_imagefov","Type":"string","Key":"","Value":"0","Category":"Others"}
##!--{"Name":"gs_clipimagewidth","Type":"string","Key":"","Value":"0","Category":"Others"}
##!--{"Name":"gs_clipimageheight","Type":"string","Key":"","Value":"0","Category":"Others"}
##[--{"OutputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output_image","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"InputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"3648297982","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"OutputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"Load","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null},"InputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"GrayToRGB","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null}}
##[--{"OutputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output_image_1","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"InputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"3662200823","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"OutputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"GrayToRGB","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null},"InputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"RGBToGray","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null}}
##[--{"OutputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output_image_2","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"InputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"4075499925","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"OutputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"RGBToGray","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null},"InputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"Bitwise_OR","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null}}
##[--{"OutputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output_image","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"InputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"4075499926","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"OutputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"Load","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null},"InputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"Bitwise_OR","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null}}
##[--{"OutputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output_image_3","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"InputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"4452988040","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"OutputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"Bitwise_OR","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null},"InputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"OtsuThresholdValue","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null}}
##[--{"OutputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"threshold","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"InputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"4415797494","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"OutputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"OtsuThresholdValue","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null},"InputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"IntensityThresholding","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null}}
##[--{"OutputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output_image","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"InputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"4415797493","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"OutputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"Load","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null},"InputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"IntensityThresholding","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null}}
##[--{"OutputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"binarization_image","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"InputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"4362679542","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"OutputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"IntensityThresholding","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null},"InputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"RegionExtraction","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null}}
##[--{"OutputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"binarization_image","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"InputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"6272029181","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"OutputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"IntensityThresholding","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null},"InputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"customFunction5","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null}}
##[--{"OutputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"binarization_image","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"InputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"6233412486","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"OutputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"IntensityThresholding","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null},"InputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"customFunction3","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null}}
##[--{"OutputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output1","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"InputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"6389395245","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"OutputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"customFunction3","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null},"InputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"Bitwise_XOR","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null}}
##[--{"OutputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"binarization_image","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"InputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"6233412487","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"OutputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"IntensityThresholding","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null},"InputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"customFunction3","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null}}
##[--{"OutputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output2","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"InputProperty":{"Name":"","Alias":"","Type":"","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"6389395246","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},"OutputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"customFunction3","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null},"InputModule":{"Name":null,"Description":null,"Inputs":[],"Outputs":[],"Category":null,"Module":null,"Key":"Bitwise_XOR","X":0,"Y":0,"Width":0,"Height":0,"Code":null,"ModuleGroup":null}}
##{--
import mpp
import cv2
gv = {}
class A():
	def Foo1(input1):
		output1
		
	def Foo2(input1):
		output1

##@--
def customFunction3(input1, input2, input3):
	output1 = input1
	output2 = input2
	output3 = input3
	lst = [1,2,3,4,5]
	return output1, output2, output3

##@--
def customFunction5(input1, input2, input3, input4, input5):
	output1 = input1
	output2 = input2
	output3 = input3
	output4 = input4
	output5 = input5
	return output1, output2, output3, output4, output5

##}--
def RecipeRun(gs_semimage1,gs_semimage2,gs_semimage3,gs_semimage4,gs_semimage5,gs_semimage6,gs_semimage7,gs_semimage8,gs_semimage9,gs_semimage10,gs_layercount,gs_layerimage1,gs_layerindex1,gs_refimage1,gs_refvector1,gs_layerimage2,gs_layerindex2,gs_refimage2,gs_refvector2,gs_layerimage3,gs_layerindex3,gs_refimage3,gs_refvector3,gs_layerimage4,gs_layerindex4,gs_refimage4,gs_refvector4,gs_layerimage5,gs_layerindex5,gs_refimage5,gs_refvector5,gs_layerimage6,gs_layerindex6,gs_refimage6,gs_refvector6,gs_layerimage7,gs_layerindex7,gs_refimage7,gs_refvector7,gs_layerimage8,gs_layerindex8,gs_refimage8,gs_refvector8,gs_layerimage9,gs_layerindex9,gs_refimage9,gs_refvector9,gs_layerimage10,gs_layerindex10,gs_refimage10,gs_refvector10,gs_layerimage11,gs_layerindex11,gs_refimage11,gs_refvector11,gs_layerimage12,gs_layerindex12,gs_refimage12,gs_refvector12,gs_layerimage13,gs_layerindex13,gs_refimage13,gs_refvector13,gs_layerimage14,gs_layerindex14,gs_refimage14,gs_refvector14,gs_layerimage15,gs_layerindex15,gs_refimage15,gs_refvector15,gs_layerimage16,gs_layerindex16,gs_refimage16,gs_refvector16,gs_layerimage17,gs_layerindex17,gs_refimage17,gs_refvector17,gs_layerimage18,gs_layerindex18,gs_refimage18,gs_refvector18,gs_layerimage19,gs_layerindex19,gs_refimage19,gs_refvector19,gs_layerimage20,gs_layerindex20,gs_refimage20,gs_refvector20,gs_resultimageurl,gs_resultdataurl,gs_resultimageextension,gs_waferid,gs_defectid,gs_xreal,gs_yreal,gs_scale,gs_xindex,gs_yindex,gs_particlecode,gs_angle,gs_clipimagewidth,gs_clipimageheight,gs_imagefov):
	resultdata = None
	import Core
##<--{"Name":"Load","Description":"","Inputs":[{"Name":"path","Alias":"Path","Type":"Global","Value":"gs_semimage1","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":true,"Key":"3598361537","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},{"Name":"gray_mode","Alias":"Gray Mode","Type":"Bool","Value":"True","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":true,"Key":"3598361538","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false}],"Outputs":[{"Name":"output","Alias":"Output","Type":"NdArray","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output_image","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false}],"Category":"Core","Module":"BasicOperation","Key":"Load","X":9035,"Y":4254,"Width":0,"Height":0,"Code":"def Load(path, gray_mode):\r\n    \"\"\"\r\n    입력 경로의 파일에서 이미지 데이터를 읽어온다.\r\n\r\n    이미지는 1채널 이미지와 3채널(B,G,R) 이미지로 읽어올 수 있다.\r\n    읽어오는 방식은 인자 `gray_mode`의 값에 따라 아래와 같이 처리된다.\r\n\r\n    - ``True`` : 1채널 이미지로 읽어온다.\r\n    - ``False`` : 3채널(B,G,R) 이미지로 읽어온다.\r\n\r\n    Parameters\r\n    ----------\r\n    path : str\r\n        이미지 파일 경로\r\n    gray_mode : bool\r\n        True 이면 이미지를 1채널 이미지로 읽어온다.(False는 원본 이미지 그대로 읽음)\r\n\r\n    Returns\r\n    -------\r\n    ndarray\r\n        출력 이미지 버퍼\r\n\r\n    See Also\r\n    -------\r\n    - ``mpp.intel64.load``\r\n\r\n    \"\"\"    \r\n    if os.path.exists(path) is False:\r\n        raise NameError('Path Error')\r\n    output = mpp.intel64.load(path, gray_mode)\r\n    \r\n    if output is None:\r\n        raise NameError('API Execution Failed')\r\n\r\n    return output\r\n","ModuleGroup":null}
	output_image = Core.BasicOperation.Load( gs_semimage1, True)
##<--{"Name":"GrayToRGB","Description":null,"Inputs":[{"Name":"input","Alias":"Input","Type":"NdArray","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"3648297982","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":true}],"Outputs":[{"Name":"output","Alias":"Output","Type":"NdArray","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output_image_1","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false}],"Category":"Core","Module":"BasicOperation","Key":"GrayToRGB","X":8756,"Y":4394,"Width":0,"Height":0,"Code":"def GrayToRGB(input):\r\n    \"\"\"\r\n    1채널 이미지를 3채널(R,G,B) 이미지로 변환한다.\r\n\r\n    Parameters\r\n    ----------\r\n    input : ndarray\r\n        1채널 입력 이미지\r\n\r\n    Returns\r\n    -------\r\n    ndarray\r\n        3채널(R,G,B) 출력 이미지 버퍼\r\n\r\n    See Also\r\n    -------\r\n    - ``mpp.intel64.gray_to_rgb``\r\n        \r\n    \"\"\"    \r\n    output = mpp.intel64.gray_to_rgb(input)\r\n\r\n    return output\r\n","ModuleGroup":null}
	output_image_1 = Core.BasicOperation.GrayToRGB( output_image)
##<--{"Name":"RGBToGray","Description":null,"Inputs":[{"Name":"input","Alias":"Input","Type":"NdArray","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"3662200823","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":true}],"Outputs":[{"Name":"output","Alias":"Output","Type":"NdArray","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output_image_2","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false}],"Category":"Core","Module":"BasicOperation","Key":"RGBToGray","X":8772,"Y":4619,"Width":0,"Height":0,"Code":"def RGBToGray(input):\r\n    \"\"\"\r\n    3채널(R,G,B) 이미지를 1채널 이미지로 변환한다.\r\n\r\n    Parameters\r\n    ----------\r\n    input : ndarray\r\n        3채널(R,G,B) 입력 이미지 버퍼\r\n\r\n    Returns\r\n    -------\r\n    ndarray\r\n        출력 이미지\r\n\r\n    See Also\r\n    -------\r\n    - ``mpp.intel64.rgb_to_gray``\r\n\r\n    \"\"\"    \r\n\r\n    output = mpp.intel64.rgb_to_gray(input)\r\n    return output\r\n","ModuleGroup":null}
	output_image_2 = Core.BasicOperation.RGBToGray( output_image_1)
##<--{"Name":"BitwiseOR","Description":"","Inputs":[{"Name":"input1","Alias":"Input1","Type":"NdArray","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"4075499925","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":true},{"Name":"input2","Alias":"Input2","Type":"NdArray","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"4075499926","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":true}],"Outputs":[{"Name":"output","Alias":"Output","Type":"NdArray","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output_image_3","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false}],"Category":"Core","Module":"BasicOperation","Key":"Bitwise_OR","X":8930,"Y":4803,"Width":0,"Height":0,"Code":"def BitwiseOR(input1, input2):\r\n    \"\"\"\r\n    동일 크기와 타입의 입력1 이미지에서 입력2 이미지의 서로 대응되는 위치의 픽셀 값을 OR 연산한다.\r\n\r\n    Parameters\r\n    ----------\r\n    input1 : ndarray\r\n        입력1 이미지 버퍼\r\n    input2 : ndarray\r\n        입력2 이미지 버퍼\r\n\r\n    Returns\r\n    -------\r\n    ndarray\r\n        출력 이미지 버퍼\r\n\r\n    See Also\r\n    -------\r\n    - ``mpp.intel64.bitwise_or``\r\n\r\n    \"\"\"\r\n    output = mpp.intel64.bitwise_or(input1, input2)\r\n    \r\n    return output\r\n","ModuleGroup":null}
	output_image_3 = Core.BasicOperation.BitwiseOR( output_image_2, output_image)
##<--{"Name":"OtsuThresholdValue","Description":null,"Inputs":[{"Name":"input","Alias":"Input","Type":"NdArray","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"4452988040","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":true}],"Outputs":[{"Name":"output","Alias":"Output","Type":"Int","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"threshold","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false}],"Category":"Core","Module":"Segmentation","Key":"OtsuThresholdValue","X":8917,"Y":4973,"Width":0,"Height":0,"Code":"def OtsuThresholdValue(input):\r\n    \"\"\"\r\n    입력 이미지를 이진화 하기 위한 픽셀의 임계값을 구한다.\r\n\r\n    입력 이미지 내 배경의 픽셀값과 전경의 픽셀값 범위가 상이할 경우, \r\n    히스토그램 상에서 두 그룹을 나누는 임계값을 구한다(Otsu Algorithm)\r\n\r\n    Parameters\r\n    ----------\r\n    input : ndarray\r\n        입력 이미지\r\n\r\n    Returns\r\n    -------\r\n    int\r\n        픽셀 임계값\r\n\r\n    See Also\r\n    --------\r\n        - ``mpp.intel64.otsu_threshold_value_by_image``\r\n    \"\"\"\r\n    output = mpp.intel64.otsu_threshold_value_by_image(input)\r\n    return output\r\n","ModuleGroup":null}
	threshold = Core.Segmentation.OtsuThresholdValue( output_image_3)
##<--{"Name":"IntensityThresholding","Description":null,"Inputs":[{"Name":"input","Alias":"Input","Type":"NdArray","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"4415797493","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":true},{"Name":"threshold","Alias":"Threshold","Type":"Int","Value":"0","MinValue":"0","MaxValue":"255","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"4415797494","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":true},{"Name":"option","Alias":"Option","Type":"List","Value":"\"greater_equal\"","MinValue":"","MaxValue":"","Items":["\"less\"","\"less_equal\"","\"equal\"","\"greater\"","\"greater_equal\""],"DefaultValue":"","IsUsercontrol":true,"Key":"4415797495","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},{"Name":"rois","Alias":"ROIs","Type":"ROIs","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"4415797496","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":true}],"Outputs":[{"Name":"output","Alias":"Output","Type":"NdArray","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"binarization_image","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false}],"Category":"Core","Module":"Segmentation","Key":"IntensityThresholding","X":9115,"Y":5133,"Width":0,"Height":0,"Code":"def IntensityThresholding(input, threshold, option, rois):\r\n    \"\"\"\r\n    입력 이미지를 임계값 `threshold`와  조건 `option` 값에 따라 이진화한다.\r\n\r\n    Parameters\r\n    ----------\r\n    input : ndarray\r\n        1채널 입력 이미지\r\n    threshold : int\r\n        임계값\r\n    option : str\r\n        임계값에 대한 적용방식. `\"\"less\"``, ``\"less_equal\"``, ``\"equal\"`, ``\"greater\"``, ``\"greater_equal\"`` 중 하나.\r\n    rois : dict\r\n        처리 할 ROI 영역 정보 목록 <br/> (``Dict[str, Dict[str, Tuple[int,int,int,int]]]`` 형태)\r\n\r\n    Returns\r\n    -------\r\n    ndarray\r\n        출력 이미지(이진화 이미지)\r\n\r\n    See Also\r\n    --------\r\n        - ``mpp.intel64.intensity_thresholding``\r\n        - ``mpp.intel64.intensity_thresholding_rois``\r\n    \"\"\"\r\n\r\n    if rois is None:\r\n        output = mpp.intel64.intensity_thresholding(input, threshold, option)\r\n    else:\r\n        output = mpp.intel64.intensity_thresholding_rois(input, threshold, option, rois)\r\n    \r\n    return output\r\n","ModuleGroup":null}
	binarization_image = Core.Segmentation.IntensityThresholding( output_image, threshold, "greater_equal", None)
##<--{"Name":"customFunction3","Description":null,"Inputs":[{"Name":"input1","Alias":"input1","Type":"Object","Value":"","MinValue":null,"MaxValue":null,"Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"6233412486","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},{"Name":"input2","Alias":"input2","Type":"Object","Value":"","MinValue":null,"MaxValue":null,"Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"6233412487","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},{"Name":"input3","Alias":"input3","Type":"Object","Value":"","MinValue":null,"MaxValue":null,"Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"6233412488","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false}],"Outputs":[{"Name":"output1","Alias":"output1","Type":"Object","Value":null,"MinValue":null,"MaxValue":null,"Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output1","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},{"Name":"output2","Alias":"output2","Type":"Object","Value":null,"MinValue":null,"MaxValue":null,"Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output2","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},{"Name":"output3","Alias":"output3","Type":"Object","Value":null,"MinValue":null,"MaxValue":null,"Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output3","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false}],"Category":"Core","Module":"UserFunction","Key":"customFunction3","X":8829,"Y":5486,"Width":0,"Height":0,"Code":null,"ModuleGroup":null}
	output1, output2, output3 = customFunction3( binarization_image, binarization_image, None)
##<--{"Name":"BitwiseXOR","Description":null,"Inputs":[{"Name":"input1","Alias":"Input1","Type":"NdArray","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"6389395245","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":true},{"Name":"input2","Alias":"Input2","Type":"NdArray","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"6389395246","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":true}],"Outputs":[{"Name":"output","Alias":"Output","Type":"NdArray","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output_image_4","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false}],"Category":"Core","Module":"BasicOperation","Key":"Bitwise_XOR","X":9005,"Y":5768,"Width":0,"Height":0,"Code":"def BitwiseXOR(input1, input2):\r\n    \"\"\"\r\n    동일 크기와 타입의 입력1 이미지에서 입력2 이미지의 서로 대응되는 위치의 픽셀 값을 XOR 연산한다.\r\n\r\n    Parameters\r\n    ----------\r\n    input1 : ndarray\r\n        입력1 이미지 버퍼\r\n    input2 : ndarray\r\n        입력2 이미지 버퍼\r\n\r\n    Returns\r\n    -------\r\n    ndarray\r\n        출력 이미지 버퍼\r\n\r\n    See Also\r\n    -------\r\n    - ``mpp.intel64.bitwise_xor``\r\n\r\n    \"\"\"    \r\n    output = mpp.intel64.bitwise_xor(input1, input2)\r\n    \r\n    return output\r\n","ModuleGroup":null}
	output_image_4 = Core.BasicOperation.BitwiseXOR( output1, output2)
##<--{"Name":"RegionsExtraction","Description":null,"Inputs":[{"Name":"binary_image","Alias":"Binary Image","Type":"NdArray","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"4362679542","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":true},{"Name":"connectivity","Alias":"Connectivity","Type":"List","Value":"4","MinValue":"","MaxValue":"","Items":["4","8"],"DefaultValue":"","IsUsercontrol":true,"Key":"4362679543","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":true}],"Outputs":[{"Name":"regions","Alias":"Regions","Type":"Regions","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"regions","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":true},{"Name":"regions_count","Alias":"Regions Count","Type":"Int","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"regions_count","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":true}],"Category":"Core","Module":"RegionAnalysis","Key":"RegionExtraction","X":9170,"Y":5302,"Width":0,"Height":0,"Code":"def RegionsExtraction(binary_image, connectivity):\r\n    \"\"\"\r\n    1채널 입력 이미지(이진화 이미지)에서 영역 정보를 추출한다.\r\n\r\n    Parameters\r\n    ----------\r\n    binary_image : ndarray\r\n        입력 이미지\r\n    connectivity : int\r\n        영역의 픽셀들을 합칠 때 고려할 방향. 4 또는 8의 값\r\n\r\n    Returns\r\n    -------\r\n    Tuple[mpp.Regions, int]\r\n        - 추출된 영역들의 목록에 대한 데이터 객체\r\n        - 추출된 영역 갯수\r\n\r\n    See Also\r\n    --------\r\n        - ``mpp.intel64.regions_extraction``\r\n    \"\"\"    \r\n    regions = mpp.intel64.regions_extraction(binary_image, connectivity)\r\n    regions_count = len(regions) \r\n\r\n    return regions , regions_count\r\n","ModuleGroup":null}
	regions, regions_count = Core.RegionAnalysis.RegionsExtraction( binarization_image, 4)
##<--{"Name":"customFunction5","Description":null,"Inputs":[{"Name":"input1","Alias":"input1","Type":"Object","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"6272029181","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},{"Name":"input2","Alias":"input2","Type":"Object","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"6272029182","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},{"Name":"input3","Alias":"input3","Type":"Object","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"6272029183","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},{"Name":"input4","Alias":"input4","Type":"Object","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"6272029184","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},{"Name":"input5","Alias":"input5","Type":"Object","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"6272029185","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false}],"Outputs":[{"Name":"output1","Alias":"output1","Type":"Object","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output1_1","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},{"Name":"output2","Alias":"output2","Type":"Object","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output2_1","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},{"Name":"output3","Alias":"output3","Type":"Object","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output3_1","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},{"Name":"output4","Alias":"output4","Type":"Object","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output4","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false},{"Name":"output5","Alias":"output5","Type":"Object","Value":"","MinValue":"","MaxValue":"","Items":[],"DefaultValue":"","IsUsercontrol":false,"Key":"output5","DependentPropertyName":"","DependentPropertyValue":"","IsNotUseTrackbar":false}],"Category":"Core","Module":"UserFunction","Key":"customFunction5","X":9469,"Y":5264,"Width":0,"Height":0,"Code":null,"ModuleGroup":null}
	output1_1, output2_1, output3_1, output4, output5 = customFunction5( binarization_image, None, None, None, None)
	return resultdata ### _main_return_

if __name__ == "__main__" :
	resultdata = RecipeRun(gs_semimage1,gs_semimage2,gs_semimage3,gs_semimage4,gs_semimage5,gs_semimage6,gs_semimage7,gs_semimage8,gs_semimage9,gs_semimage10,gs_layercount,gs_layerimage1,gs_layerindex1,gs_refimage1,gs_refvector1,gs_layerimage2,gs_layerindex2,gs_refimage2,gs_refvector2,gs_layerimage3,gs_layerindex3,gs_refimage3,gs_refvector3,gs_layerimage4,gs_layerindex4,gs_refimage4,gs_refvector4,gs_layerimage5,gs_layerindex5,gs_refimage5,gs_refvector5,gs_layerimage6,gs_layerindex6,gs_refimage6,gs_refvector6,gs_layerimage7,gs_layerindex7,gs_refimage7,gs_refvector7,gs_layerimage8,gs_layerindex8,gs_refimage8,gs_refvector8,gs_layerimage9,gs_layerindex9,gs_refimage9,gs_refvector9,gs_layerimage10,gs_layerindex10,gs_refimage10,gs_refvector10,gs_layerimage11,gs_layerindex11,gs_refimage11,gs_refvector11,gs_layerimage12,gs_layerindex12,gs_refimage12,gs_refvector12,gs_layerimage13,gs_layerindex13,gs_refimage13,gs_refvector13,gs_layerimage14,gs_layerindex14,gs_refimage14,gs_refvector14,gs_layerimage15,gs_layerindex15,gs_refimage15,gs_refvector15,gs_layerimage16,gs_layerindex16,gs_refimage16,gs_refvector16,gs_layerimage17,gs_layerindex17,gs_refimage17,gs_refvector17,gs_layerimage18,gs_layerindex18,gs_refimage18,gs_refvector18,gs_layerimage19,gs_layerindex19,gs_refimage19,gs_refvector19,gs_layerimage20,gs_layerindex20,gs_refimage20,gs_refvector20,gs_resultimageurl,gs_resultdataurl,gs_resultimageextension,gs_waferid,gs_defectid,gs_xreal,gs_yreal,gs_scale,gs_xindex,gs_yindex,gs_particlecode,gs_angle,gs_clipimagewidth,gs_clipimageheight,gs_imagefov)

